import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import SeverityBadge from "./SeverityBadge";
import { getEquipmentProfile, getHistory } from "../utils/api";

export default function EquipmentDetail() {
  const { equipmentId } = useParams();
  const [profile, setProfile] = useState(null);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      setLoading(true);
      try {
        const [profileData, historyData] = await Promise.allSettled([
          getEquipmentProfile(equipmentId),
          getHistory(equipmentId),
        ]);

        if (profileData.status === "fulfilled") {
          setProfile(profileData.value);
        }
        if (historyData.status === "fulfilled") {
          setHistory(historyData.value.results || []);
        }
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [equipmentId]);

  if (loading) {
    return (
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="h-7 w-48 skeleton rounded" />
        <div className="h-4 w-32 skeleton rounded" />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-white border border-surface-200 rounded-lg p-5 space-y-3">
            <div className="h-4 w-24 skeleton rounded" />
            <div className="h-3 w-full skeleton rounded" />
            <div className="h-3 w-3/4 skeleton rounded" />
          </div>
          <div className="bg-white border border-surface-200 rounded-lg p-5 space-y-3">
            <div className="h-4 w-24 skeleton rounded" />
            <div className="h-3 w-full skeleton rounded" />
          </div>
        </div>
      </div>
    );
  }

  const staticFacts = profile?.profile?.static || [];
  const dynamicFacts = profile?.profile?.dynamic || [];

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-surface-900">{equipmentId}</h1>
          <p className="mt-0.5 text-sm text-surface-400">Equipment profile & inspection history</p>
        </div>
        <Link
          to="/inspect"
          className="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-md bg-cat text-navy-900 hover:bg-cat-600 transition-colors shadow-sm"
        >
          Inspect Now
        </Link>
      </div>

      {/* Profile cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Static facts */}
        <div className="bg-white border border-surface-200 rounded-lg shadow-sm">
          <div className="px-5 py-4 border-b border-surface-200">
            <h3 className="text-sm font-semibold text-surface-800">Equipment Profile</h3>
            <p className="text-xs text-surface-400 mt-0.5">
              Long-term facts auto-generated by Supermemory
            </p>
          </div>
          <div className="px-5 py-4">
            {staticFacts.length > 0 ? (
              <ul className="space-y-2">
                {staticFacts.map((f, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-surface-700">
                    <span className="w-1.5 h-1.5 mt-1.5 rounded-full bg-navy flex-shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-surface-400 text-center py-4">
                No profile data yet. Run an inspection to build this equipment's profile.
              </p>
            )}
          </div>
        </div>

        {/* Dynamic context */}
        <div className="bg-white border border-surface-200 rounded-lg shadow-sm">
          <div className="px-5 py-4 border-b border-surface-200">
            <h3 className="text-sm font-semibold text-surface-800">Recent Context</h3>
            <p className="text-xs text-surface-400 mt-0.5">Latest activity and observations</p>
          </div>
          <div className="px-5 py-4">
            {dynamicFacts.length > 0 ? (
              <ul className="space-y-2">
                {dynamicFacts.map((f, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-surface-700">
                    <span className="w-1.5 h-1.5 mt-1.5 rounded-full bg-cat flex-shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-surface-400 text-center py-4">
                No recent context available.
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Inspection history */}
      <div className="bg-white border border-surface-200 rounded-lg shadow-sm overflow-hidden">
        <div className="px-5 py-4 border-b border-surface-200">
          <h3 className="text-sm font-semibold text-surface-800">Inspection History</h3>
        </div>

        {history.length > 0 ? (
          <div className="divide-y divide-surface-200">
            {history.map((r, i) => {
              const text =
                typeof r.memory === "string"
                  ? r.memory
                  : typeof r.chunk === "string"
                  ? r.chunk
                  : JSON.stringify(r);
              const severity = r.metadata?.severity;
              const date = r.metadata?.date;

              return (
                <div key={i} className="px-5 py-4">
                  <div className="flex items-center justify-between mb-1">
                    <p className="text-xs text-surface-400">
                      {date ? new Date(date).toLocaleString() : `Inspection #${i + 1}`}
                    </p>
                    {severity && <SeverityBadge severity={severity} />}
                  </div>
                  <p className="text-sm text-surface-700 leading-relaxed">{text}</p>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="text-center py-12 px-5">
            <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-navy-50 mx-auto mb-3">
              <svg className="w-6 h-6 text-navy-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <p className="text-sm font-medium text-surface-700">No inspection history</p>
            <p className="text-xs text-surface-400 mt-1">
              This equipment hasn't been inspected yet
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
